if("undefined"===typeof THE_APP)var THE_APP={DEFAULT_MAP_POS:{lon:139.745471,lat:35.658578}};
var MainMapControl=function(){var a=null,b=null,c=null,d=null,e=function(e){if("GoogleRoad"===e)null==c&&(c=GMapControl(),c.init("gmap"),c.setCenter(THE_APP.DEFAULT_MAP_POS.lon,THE_APP.DEFAULT_MAP_POS.lat,17)),c.show(),null!=b&&b.hide(),null!=d&&d.hide(),null!=a&&a.hide();else if("Yahoo"===e)null==b&&(b=YMapControl(),b.init("ymap"),b.setCenter(THE_APP.DEFAULT_MAP_POS.lon,THE_APP.DEFAULT_MAP_POS.lat,17)),b.show(),null!=c&&c.hide(),null!=d&&d.hide(),null!=a&&a.hide();else if("ZDC"===e)null==d&&(d=ZMapControl(),
d.init("zmap"),d.setCenter(THE_APP.DEFAULT_MAP_POS.lon,THE_APP.DEFAULT_MAP_POS.lat,14)),d.show(),null!=c&&c.hide(),null!=b&&b.hide(),null!=a&&a.hide();else{if(null==a){a=OMapControl();a.init("omap");var f=a.getMap();GMap().init(f);GSMap().init(f,function(){a.changeBaseLayer(e)});OSMMap().init(f);CJMMap().init(f);a.setCenter(THE_APP.DEFAULT_MAP_POS.lon,THE_APP.DEFAULT_MAP_POS.lat,17)}a.changeBaseLayer(e);a.show();null!=c&&c.hide();null!=b&&b.hide();null!=d&&d.hide()}};return{init:function(){e("GoogleRoad")},
change:e}},GMapControl=function(){var a=null,b=null;return{init:function(c){a=c;var d={zoom:12,center:new google.maps.LatLng(THE_APP.DEFAULT_MAP_POS.lat,THE_APP.DEFAULT_MAP_POS.lon),mapTypeId:google.maps.MapTypeId.ROADMAP};b=new google.maps.Map(document.getElementById(c),d)},show:function(){$("#"+a).css("display","block")},hide:function(){$("#"+a).css("display","none")},setCenter:function(a,d,e){a=new google.maps.LatLng(35.658517,139.745493);b.setCenter(a);b.setZoom(e)}}},ZMapControl=function(){var a=
null,b=null;return{init:function(c){a=c;b=new ZDC.Map(document.getElementById(a),{mapType:ZDC.MAPTYPE_COLOR});c=new ZDC.Control({pos:{top:10,left:10},type:ZDC.CTRL_TYPE_SMALL});b.addWidget(c)},show:function(){$("#"+a).css("display","block")},hide:function(){$("#"+a).css("display","none")},setCenter:function(a,d,e){b.moveLatLon(new ZDC.LatLon(d,a));b.setZoom(e)}}},YMapControl=function(){var a=null,b=null;return{init:function(c){a=c;b=new Y.Map(c);b.addControl(new Y.LayerSetControl);b.addControl(new Y.ScaleControl);
b.addControl(new Y.SliderZoomControlVertical)},show:function(){$("#"+a).css("display","block")},hide:function(){$("#"+a).css("display","none")},setCenter:function(a,d,e){b.drawMap(new Y.LatLng(d,a),e,Y.LayerSetId.NORMAL)}}},OMapControl=function(){var a=null,b=null,c=new OpenLayers.Projection("EPSG:3857"),d=new OpenLayers.Projection("EPSG:4326");return{init:function(e){a=e;var g={units:"m",projection:c,displayProjection:d,maxResolution:78271.52,numZoomLevels:19,maxExtent:new OpenLayers.Bounds(-2.003750834E7,
-2.003750834E7,2.003750834E7,2.003750834E7),controls:[]};b=new OpenLayers.Map(e,g);b.addControl(new OpenLayers.Control.ScaleLine);b.addControl(new OpenLayers.Control.MousePosition);b.addControl(new OpenLayers.Control.Navigation);b.addControl(new OpenLayers.Control.Zoom);b.addControl(new OpenLayers.Control.Attribution)},getMap:function(){return b},setCenter:function(a,c,f){a=(new OpenLayers.LonLat(a,c)).transform(d,b.getProjectionObject());b.setCenter(a,f)},changeBaseLayer:function(a){a=b.getLayersBy("name",
a)[0];b.setBaseLayer(a)},show:function(){$("#"+a).css("display","block")},hide:function(){$("#"+a).css("display","none")},layout:function(){$("#"+a).css("width","99%");$("#"+a).css("height","99%")}}},CJMMap=function(){var a=null,b=null,c=function(){return[new OpenLayers.Layer.XYZ("CJMapStandard","http://cyberjapandata.gsi.go.jp/xyz/std/${z}/${x}/${y}.png",{attribution:"<a href='http://portal.cyberjapan.jp/help/termsofuse.html' target='_blank'>\u56fd\u571f\u5730\u7406\u9662</a>",maxZoomLevel:17})]};
return{init:function(d){a=d;b=c();a.addLayers(b)},getLayers:c}},CJMMap2=function(){var a=null,b=null,c=function(){var a=new webtis.Layer.BaseMap("CJMapStandard",{dataSet:{"0":null,1:null,2:null,3:null,4:null,5:{dataId:"JAIS"},6:{dataId:"JAIS"},7:{dataId:"JAIS"},8:{dataId:"JAIS"},9:{dataId:"BAFD1000K"},10:{dataId:"BAFD1000K"},11:{dataId:"BAFD1000K"},12:{dataId:"BAFD200K"},13:{dataId:"BAFD200K"},14:{dataId:"BAFD200K"},15:{dataId:"DJBMM"},16:{dataId:"DJBMM"},17:{dataId:"DJBMM"},18:{dataId:"FGD"}}}),
b=new webtis.Layer.BaseMap("CJMapWhite",{dataSet:{"0":null,1:null,2:null,3:null,4:null,5:{dataId:"BLANK"},6:{dataId:"BLANK"},7:{dataId:"BLANK"},8:{dataId:"BLANK"},9:{dataId:"BLANK"},10:{dataId:"BLANK"},11:{dataId:"BLANK"},12:{dataId:"BAFD200KG"},13:{dataId:"BAFD200KG"},14:{dataId:"BAFD200KG"},15:{dataId:"D25KG"},16:{dataId:"D25KG"},17:{dataId:"D25KG"},18:{dataId:"D2500G"}}});return[a,b]};return{init:function(d){a=d;b=c();a.addLayers(b)},getLayers:c}},OSMMap=function(){var a=null,b=null,c=function(){return[new OpenLayers.Layer.OSM("OSM")]};
return{init:function(d){a=d;b=c();a.addLayers(b)},getLayers:c}},GMap=function(){var a=null,b=null,c=function(){var a=new OpenLayers.Layer.Google("GoogleRoad",{type:google.maps.MapTypeId.ROAD,numZoomLevels:20}),b=new OpenLayers.Layer.Google("GoogleTerrain",{type:google.maps.MapTypeId.TERRAIN,numZoomLevels:20}),c=new OpenLayers.Layer.Google("GoogleSatellite",{type:google.maps.MapTypeId.SATELLITE,numZoomLevels:22}),f=new OpenLayers.Layer.Google("GoogleHybrid",{type:google.maps.MapTypeId.HYBRID,numZoomLevels:20});
return[a,b,f,c]};return{init:function(d){a=d;b=c();a.addLayers(b)},getLayers:c}},GSMap=function(){var a=null,b=null,c=null,d=function(){$.ajax({url:"/map/key/gs/",type:"post",dataType:"jsonp",success:function(a){c=a.authorizeKey}})},e=function(){var a=g("GeospaceRoad","road","image/png",c),b=g("GeospaceAerial","aerial","image/jpeg",c);return[a,b]},g=function(a,b,c,d){for(var e=Array(19),h=1;19>=h;h++)e[h-1]={},e[h-1].identifier=""+h;return new OpenLayers.Layer.WMTS({name:a,url:"http://cds.geospace.jp/images/wmts",
requestEncoding:"REST",layer:b,matrixSet:"EPSG3857",format:c,style:"default",matrixIds:e,isBaseLayer:!0,dimensions:["KEY"],params:{KEY:d},transitionEffect:"resize",sphericalMercator:!0,buffer:1})};return{init:function(f,g){a=f;$.ajax({url:"/map/key/gs/",type:"post",dataType:"jsonp",success:function(d){c=d.authorizeKey;b=e();a.addLayers(b);g()}});setInterval(d,36E4)},getLayers:e}};

